import { StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#141210' },
  safeArea: { flex: 1 },
  scrollContent: { paddingBottom: 24 },
  header: { paddingHorizontal: 16, marginBottom: 12 },
  title: { fontSize: 28, fontWeight: '800', color: '#fff7f2' },
  subtitle: { marginTop: 6, fontSize: 14, color: '#cbb5aa' },
  reviewCard: {
    marginTop: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#43342d',
    backgroundColor: '#211c19',
    padding: 12,
  },
  reviewTitle: { fontWeight: '700', color: '#ff8f57', marginBottom: 4 },
  reviewText: { color: '#dfc8bc', lineHeight: 20 },
  card: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: '#1d1a18',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#332b28',
  },
  sectionTitle: { fontSize: 20, fontWeight: '700', color: '#fff7f2' },
  cardSubtitle: { marginTop: 4, color: '#c8b2a6', marginBottom: 10 },
  metricRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  addRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
    alignItems: 'stretch',
  },
  addButton: { minWidth: 88, justifyContent: 'center' },
  input: {
    flex: 1,
    minWidth: 220,
    borderWidth: 1,
    borderColor: '#43342d',
    padding: 10,
    borderRadius: 9,
    backgroundColor: '#131110',
    color: '#fff7f2',
  },
  planRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    justifyContent: 'space-between',
    padding: 10,
    borderColor: '#332b28',
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: '#24201e',
    gap: 12,
  },
  planLeft: { flex: 1 },
  planTitle: { fontWeight: '600', color: '#fff7f2' },
  planHint: { color: '#c0aaa0', fontSize: 12, marginTop: 2 },
  planStatus: { fontSize: 13, fontWeight: '700', color: '#fff7f2', flexShrink: 0 },
  planStatusDone: { color: '#61c48b' },
  tunerPanel: {
    borderWidth: 1,
    borderColor: '#332b28',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    backgroundColor: '#24201e',
  },
  noteLabel: { color: '#c8b2a6', fontSize: 13 },
  noteValue: { fontSize: 30, fontWeight: '800', marginTop: 4, color: '#ff7a3d' },
  stringRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  stringButton: {
    borderWidth: 1,
    borderColor: '#43342d',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    minWidth: 82,
    alignItems: 'center',
    backgroundColor: '#161413',
  },
  stringButtonActive: { backgroundColor: '#ff7a3d', borderColor: '#ff7a3d' },
  stringText: { color: '#fff7f2', fontWeight: '600' },
  stringTextActive: { color: '#fff' },
  tunerStatus: {
    marginTop: 12,
    padding: 10,
    backgroundColor: '#131110',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#332b28',
  },
  statusLabel: { fontSize: 12, color: '#c8b2a6' },
  statusValue: { fontSize: 18, fontWeight: '700', marginBottom: 4, color: '#fff7f2' },
  statusHint: { color: '#fff7f2', fontWeight: '600' },
  buttonRow: { marginTop: 8, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  buttonCell: { flexGrow: 1, minWidth: 140 },
  secondaryButtonRow: { marginTop: 8, alignSelf: 'flex-start' },
  coachCard: {
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#43342d',
    backgroundColor: '#24201e',
    padding: 12,
  },
  coachLabel: { fontWeight: '700', color: '#ff8f57', marginBottom: 4 },
  coachText: { color: '#dfc8bc', lineHeight: 20 },
  sessionCard: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#43342d',
    borderRadius: 10,
    backgroundColor: '#24201e',
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 12,
    alignItems: 'center',
  },
  sessionSummary: { flex: 1, minWidth: 180 },
  sessionAction: { minWidth: 120 },
  sessionTitle: { fontWeight: '700', color: '#fff7f2' },
  sessionHint: { marginTop: 2, color: '#c0aaa0' },
  sessionRow: {
    borderWidth: 1,
    borderColor: '#332b28',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    backgroundColor: '#24201e',
  },
  sessionRowTitle: { fontWeight: '600', color: '#fff7f2' },
  sessionRowMeta: { fontSize: 12, color: '#c0aaa0', marginTop: 2 },
  songCard: {
    borderWidth: 1,
    borderColor: '#332b28',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    backgroundColor: '#24201e',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
  },
  songDetails: { flex: 1, minWidth: 180 },
  songAction: { alignItems: 'flex-end', minWidth: 88, marginLeft: 'auto', gap: 6 },
  songTitle: { fontWeight: '700', color: '#fff7f2' },
  songMeta: { fontSize: 12, color: '#c0aaa0' },
  songProgress: { fontWeight: '700', color: '#fff7f2' },
  proTip: {
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#43342d',
    backgroundColor: '#24201e',
    padding: 10,
  },
  tipTitle: { fontWeight: '700', color: '#ff8f57' },
  tipText: { color: '#dfc8bc', marginTop: 4 },
  analyticsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
  analyticsSummary: {
    marginTop: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#332b28',
    backgroundColor: '#24201e',
    padding: 10,
  },
  analyticsSummaryTitle: { fontWeight: '700', color: '#fff7f2', marginBottom: 4 },
  analyticsSummaryText: { color: '#c8b2a6', lineHeight: 20 },
  syncBanner: {
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2f6b50',
    backgroundColor: '#162119',
  },
  syncBannerText: { color: '#76d0a0', fontWeight: '600' },
});
